%% WP4 PPS BOOTSTRAP ANALYSIS: BASELINE vs POST-TRAINING
% Tool-mediated training intervention: PULL TRAINING
% This script follows the WP3 bootstrap analysis:
%   1. Pool trials across participants who passed baseline QC.
%   2. Resample trials with replacement separately at each distance.
%   3. Calculate the mean RT at each distance and min-max normalise it.
%   4. Fit the same two-parameter sigmoid used in WP3.
%   5. Retain bootstrap fits with R^2 >= 0.80.
%   6. Compare the Post-training and baseline bootstrap PPS-border
%      distributions following PULL TRAINING.

clear; close all; clc;

dbstop if error
% dbstop if warning

%% -------------------- USER SETTINGS --------------------

% Folder containing the WP4 CSV files and the cleaned WP4 workspace
dataFolder = '';

% The clean script saves the participant list after baseline-QC exclusions
cleanWorkspaceFile = fullfile( ...
    dataFolder,'');

% File patterns
strings = {'pre*.csv','post*.csv'};
% User-facing assessment labels. File patterns remain pre/post because they
% correspond to the existing CSV filenames.
conditionNames = {'Baseline','Post-training'};

% Distances used in the PPS task
distances = [0.25; 0.75; 1.25; 1.75; 2.25];

% Data-cleaning parameters: identical to the WP3 analysis
centralonly = 0;  % 0 = central only, 1 = all, 2 = peripheral only
cutoff = 3;       % z-score threshold for RT outliers
minimumRT = 0.1;  % seconds
maximumRT = 1.0;  % seconds

% Bootstrap parameters
nBootstrap = 12000;    % number of accepted fits per condition
minimumFitR2 = 0.80;   % same accepted-fit threshold as WP3
maxAttempts = 600000;  % prevents an infinite loop

% Set to 1 to display progress and figures
showProgress = 1;
makeFigures = 1;

%% -------------------- LOAD INCLUDED PARTICIPANTS --------------------

if ~isfile(cleanWorkspaceFile)
    error(['The cleaned workspace was not found:\n%s\n' ...
        'Run the WP4 PPS cleaning and baseline-QC script first.'], ...
        cleanWorkspaceFile);
end

cleanData = load(cleanWorkspaceFile,'name');

if ~isfield(cleanData,'name') || isempty(cleanData.name)
    error(['The cleaned workspace does not contain a non-empty ' ...
        'participant variable named ''name''.']);
end

name = cleanData.name;

nSubjects = numel(name);
nConditions = numel(strings);
nDistances = numel(distances);

fprintf('\nWP4 PPS bootstrap analysis\n');
fprintf('Participants included after baseline QC: %d\n',nSubjects);
fprintf('Included participant IDs:\n');
disp(name(:));

%% -------------------- DEFINE THE WP3 SIGMOID --------------------

% Same two-parameter logistic equation used in WP3
% b controls the slope and x0 is the estimated PPS border
eqsig = fittype( ...
    '1/(1+exp(-(x-x0)/b))', ...
    'independent','x', ...
    'coefficients',{'b','x0'});

fitOptions = fitoptions(eqsig);
fitOptions.Lower = [eps 0.25];
fitOptions.Upper = [Inf 2.25];
fitOptions.StartPoint = [0.5 1.25];

%% -------------------- LOAD AND POOL RAW TRIALS --------------------

% Each cell contains pooled rows:
% [Vibrate_distance, RT, Monster]
pooledData = cell(1,nConditions);

for s = 1:nSubjects

    for c = 1:nConditions

        files = dir(fullfile( ...
            dataFolder,[name{s} strings{c}]));

        if isempty(files)
            error('Missing file for participant %s, condition %s.', ...
                name{s},conditionNames{c});
        end

        if numel(files) > 1
            error(['More than one file was found for participant %s, ' ...
                'condition %s. Keep only one file per condition.'], ...
                name{s},conditionNames{c});
        end

        filePath = fullfile(files(1).folder,files(1).name);

        T = readtable( ...
            filePath, ...
            'VariableNamingRule','preserve');

        requiredVariables = ...
            {'Vibrate_distance','RT','Monster'};

        if ~all(ismember( ...
                requiredVariables,T.Properties.VariableNames))

            error(['Required variables are missing from %s. ' ...
                'Expected: Vibrate_distance, RT, Monster.'], ...
                files(1).name);
        end

        currentData = [ ...
            T.Vibrate_distance, ...
            T.RT, ...
            T.Monster];

        pooledData{c} = [pooledData{c}; currentData];
    end
end

%% -------------------- CLEAN THE POOLED DATA --------------------

dataByDistance = cell(nConditions,nDistances);
trialCount = nan(nConditions,nDistances);

for c = 1:nConditions

    X = pooledData{c};

    % Select central or peripheral stimuli
    if centralonly == 0
        X = X(X(:,3) == 0,:);
    elseif centralonly == 2
        X = X(X(:,3) ~= 0,:);
    end

    % Remove catch trials and tactile-only/control trials
    X(X(:,1) == -1,2) = NaN;
    X(X(:,1) == 0,2) = NaN;

    % Remove RTs outside the WP3 range
    X(X(:,2) < minimumRT,2) = NaN;
    X(X(:,2) > maximumRT,2) = NaN;

    % Remove invalid rows
    X = X(isfinite(X(:,2)),:);

    pooledData{c} = X;

    % Divide the cleaned data by distance
    for d = 1:nDistances

        dataByDistance{c,d} = ...
            X(X(:,1) == distances(d),:);

        trialCount(c,d) = ...
            size(dataByDistance{c,d},1);

        if trialCount(c,d) == 0
            error(['No valid trials remained for condition %s ' ...
                'at distance %.2f m.'], ...
                conditionNames{c},distances(d));
        end
    end
end

distanceVariableNames = matlab.lang.makeValidName( ...
    compose('Distance_%.2fm',distances));

trialCountTable = array2table( ...
    trialCount, ...
    'VariableNames',distanceVariableNames);

trialCountTable = addvars( ...
    trialCountTable, ...
    string(conditionNames(:)), ...
    'Before',1, ...
    'NewVariableNames','Condition');

fprintf('\nNumber of pooled valid trials by condition and distance:\n');
disp(trialCountTable);

writetable( ...
    trialCountTable, ...
    fullfile(dataFolder,'WP4_PPS_pooled_trial_counts.csv'));

%% -------------------- OBSERVED GROUP FITS --------------------

observedMeanRT = nan(nConditions,nDistances);
observedNormRT = nan(nConditions,nDistances);
observedBorder = nan(nConditions,1);
observedR2 = nan(nConditions,1);
observedFit = cell(nConditions,1);

for c = 1:nConditions

    for d = 1:nDistances

        trials = dataByDistance{c,d}(:,2);

        trials = remove_wp3_outliers( ...
            trials,cutoff);

        observedMeanRT(c,d) = ...
            mean(trials,'omitnan');
    end

    denominator = ...
        max(observedMeanRT(c,:)) - ...
        min(observedMeanRT(c,:));

    if ~isfinite(denominator) || denominator <= eps
        error(['Observed RT values for condition %s cannot be ' ...
            'normalised because their range is zero or invalid.'], ...
            conditionNames{c});
    end

    observedNormRT(c,:) = ...
        (observedMeanRT(c,:) - ...
        min(observedMeanRT(c,:))) ./ denominator;

    try

        [observedFit{c},goodness] = fit( ...
            distances, ...
            observedNormRT(c,:)', ...
            eqsig, ...
            fitOptions);

        observedBorder(c) = ...
            observedFit{c}.x0;

        observedR2(c) = ...
            goodness.rsquare;

    catch ME

        error('Observed sigmoid fit failed for %s: %s', ...
            conditionNames{c},ME.message);
    end
end

%% -------------------- WP3-STYLE BOOTSTRAP: BASELINE --------------------

fprintf('\nStarting baseline bootstrap: %d accepted fits required.\n', ...
    nBootstrap);

[BootAvPre, ...
 BootBorderSigPre, ...
 BootRsqSigPre, ...
 attemptsPre] = run_wp3_bootstrap( ...
    dataByDistance(1,:), ...
    distances, ...
    cutoff, ...
    nBootstrap, ...
    minimumFitR2, ...
    maxAttempts, ...
    eqsig, ...
    fitOptions, ...
    100000, ...
    showProgress, ...
    'Baseline');

%% -------------------- WP3-STYLE BOOTSTRAP: POST-TRAINING --------------------

fprintf('\nStarting Post-training bootstrap: %d accepted fits required.\n', ...
    nBootstrap);

[BootAvPost, ...
 BootBorderSigPost, ...
 BootRsqSigPost, ...
 attemptsPost] = run_wp3_bootstrap( ...
    dataByDistance(2,:), ...
    distances, ...
    cutoff, ...
    nBootstrap, ...
    minimumFitR2, ...
    maxAttempts, ...
    eqsig, ...
    fitOptions, ...
    200000, ...
    showProgress, ...
    'Post-training');

%% -------------------- BOOTSTRAP COMPARISON --------------------

% Same WP3 comparison logic, adapted to Post-training versus baseline.
% Directional hypothesis: Post-training PPS border > baseline PPS border.
diffPostPre = ...
    BootBorderSigPost - BootBorderSigPre;

% One-sided bootstrap probabilities
p_post_gt_pre = ...
    mean(diffPostPre <= 0);

p_pre_gt_post = ...
    mean(diffPostPre >= 0);

% Optional two-sided probability
p_two_sided = ...
    min(1,2*min(p_post_gt_pre,p_pre_gt_post));

% Percentile confidence intervals
ciPre = ...
    prctile(BootBorderSigPre,[2.5 97.5]);

ciPost = ...
    prctile(BootBorderSigPost,[2.5 97.5]);

ciDifference = ...
    prctile(diffPostPre,[2.5 97.5]);

observedDifference = ...
    observedBorder(2) - observedBorder(1);

%% -------------------- DISPLAY RESULTS --------------------

fprintf('\n============================================================\n');
fprintf('WP4 PPS PRELIMINARY BOOTSTRAP RESULTS\n');
fprintf('============================================================\n');

fprintf('Participants included: %d\n',nSubjects);
fprintf('Accepted bootstrap fits per condition: %d\n',nBootstrap);
fprintf('Baseline attempts required:      %d\n',attemptsPre);
fprintf('Post-training attempts required: %d\n',attemptsPost);

fprintf('\nObserved sigmoid fits:\n');

fprintf('Baseline PPS border:      %.4f m (R^2 = %.4f)\n', ...
    observedBorder(1),observedR2(1));

fprintf('Post-training PPS border: %.4f m (R^2 = %.4f)\n', ...
    observedBorder(2),observedR2(2));

fprintf('Observed Post-training - baseline difference: %.4f m\n', ...
    observedDifference);

fprintf('\nBootstrap PPS-border distributions:\n');

fprintf('Baseline mean:      %.4f m; 95%% CI [%.4f, %.4f]\n', ...
    mean(BootBorderSigPre), ...
    ciPre(1), ...
    ciPre(2));

fprintf('Post-training mean: %.4f m; 95%% CI [%.4f, %.4f]\n', ...
    mean(BootBorderSigPost), ...
    ciPost(1), ...
    ciPost(2));

fprintf('Post-training - baseline mean difference: %.4f m\n', ...
    mean(diffPostPre));

fprintf('95%% CI for Post-training - baseline: [%.4f, %.4f]\n', ...
    ciDifference(1), ...
    ciDifference(2));

fprintf('\nOne-sided p (Post-training > baseline): %.5f\n', ...
    p_post_gt_pre);

fprintf('One-sided p (baseline > Post-training): %.5f\n', ...
    p_pre_gt_post);

fprintf('Optional two-sided p:     %.5f\n', ...
    p_two_sided);

fprintf('============================================================\n');

%% -------------------- SAVE NUMERICAL OUTPUTS --------------------

resultsTable = table( ...
    string(conditionNames(:)), ...
    observedBorder, ...
    observedR2, ...
    [mean(BootBorderSigPre); ...
     mean(BootBorderSigPost)], ...
    [median(BootBorderSigPre); ...
     median(BootBorderSigPost)], ...
    [ciPre(1); ciPost(1)], ...
    [ciPre(2); ciPost(2)], ...
    'VariableNames', ...
    {'Condition', ...
     'ObservedPPSBorder_m', ...
     'ObservedR2', ...
     'BootstrapMeanBorder_m', ...
     'BootstrapMedianBorder_m', ...
     'CI95_Lower_m', ...
     'CI95_Upper_m'});

writetable( ...
    resultsTable, ...
    fullfile( ...
        dataFolder, ...
        'WP4_PPS_bootstrap_summary.csv'));

differenceTable = table( ...
    observedDifference, ...
    mean(diffPostPre), ...
    median(diffPostPre), ...
    ciDifference(1), ...
    ciDifference(2), ...
    p_post_gt_pre, ...
    p_pre_gt_post, ...
    p_two_sided, ...
    'VariableNames', ...
    {'ObservedDifference_m', ...
     'BootstrapMeanDifference_m', ...
     'BootstrapMedianDifference_m', ...
     'CI95_Lower_m', ...
     'CI95_Upper_m', ...
     'P_PostTrainingGreaterThanBaseline', ...
     'P_BaselineGreaterThanPostTraining', ...
     'P_TwoSided'});

writetable( ...
    differenceTable, ...
    fullfile( ...
        dataFolder, ...
        'WP4_PPS_bootstrap_difference.csv'));

save( ...
    fullfile( ...
        dataFolder, ...
        'WP4_PPS_bootstrap_results.mat'), ...
    'name', ...
    'nSubjects', ...
    'distances', ...
    'trialCount', ...
    'observedMeanRT', ...
    'observedNormRT', ...
    'observedBorder', ...
    'observedR2', ...
    'observedDifference', ...
    'BootAvPre', ...
    'BootBorderSigPre', ...
    'BootRsqSigPre', ...
    'BootAvPost', ...
    'BootBorderSigPost', ...
    'BootRsqSigPost', ...
    'diffPostPre', ...
    'ciPre', ...
    'ciPost', ...
    'ciDifference', ...
    'p_post_gt_pre', ...
    'p_pre_gt_post', ...
    'p_two_sided', ...
    'nBootstrap', ...
    'minimumFitR2', ...
    'attemptsPre', ...
    'attemptsPost');

%% -------------------- FIGURES --------------------

if makeFigures == 1

    % WP3 colour convention:
    %   BASELINE = red; POST-TRAINING following PULL TRAINING = blue.
    colourPre = [1.00 0.10 0.10];
    colourPost = [0.10 0.15 1.00];

    %% Figure 1: observed normalised data and sigmoid fits

    figFit = figure(1);
    clf(figFit);
    set(figFit,'Color','w','Position',[100 100 535 510]);
    axesFit = axes('Parent',figFit); %#ok<LAXES>
    hold(axesFit,'on');

    xx = linspace( ...
        min(distances), ...
        max(distances), ...
        400);

    plot( ...
        axesFit, ...
        xx, ...
        feval(observedFit{1},xx), ...
        'Color',colourPre, ...
        'LineWidth',3, ...
        'HandleVisibility','off');

    plot( ...
        axesFit, ...
        xx, ...
        feval(observedFit{2},xx), ...
        'Color',colourPost, ...
        'LineWidth',3, ...
        'HandleVisibility','off');

    hPreData = plot( ...
        axesFit, ...
        distances, ...
        observedNormRT(1,:), ...
        'o', ...
        'LineStyle','none', ...
        'Color',colourPre, ...
        'MarkerFaceColor','none', ...
        'MarkerEdgeColor',colourPre, ...
        'MarkerSize',8, ...
        'LineWidth',1.6);

    hPostData = plot( ...
        axesFit, ...
        distances, ...
        observedNormRT(2,:), ...
        'o', ...
        'LineStyle','none', ...
        'Color',colourPost, ...
        'MarkerFaceColor','none', ...
        'MarkerEdgeColor',colourPost, ...
        'MarkerSize',8, ...
        'LineWidth',1.6);

    % WP3-style double-headed indicators for the fitted PPS borders.
    draw_wp3_border_arrow( ...
        axesFit,observedBorder(1),colourPre,0.14);
    draw_wp3_border_arrow( ...
        axesFit,observedBorder(2),colourPost,0.14);

    xlabel(axesFit,'Distance (m)');
    ylabel(axesFit,'RTs (norm)');
    xlim(axesFit,[0.22 2.28]);
    ylim(axesFit,[0 1.02]);
    xticks(axesFit,distances);
    xticklabels(axesFit,compose('%.2f',distances));
    yticks(axesFit,0:0.25:1);
    style_wp3_axes(axesFit);

    legend( ...
        axesFit, ...
        [hPreData,hPostData], ...
        {'BASELINE','POST-TRAINING'}, ...
        'Location','northwest', ...
        'Box','on', ...
        'FontSize',8);

    text(axesFit,0.97,0.97,'b', ...
        'Units','normalized', ...
        'HorizontalAlignment','right', ...
        'VerticalAlignment','top', ...
        'FontSize',13, ...
        'FontName','Arial');

    %% Figure 2: WP3-style bootstrap border distributions

    figBorders = figure(2);
    clf(figBorders);
    set(figBorders,'Color','w','Position',[100 100 535 510]);
    axesBorders = axes('Parent',figBorders); %#ok<LAXES>
    hold(axesBorders,'on');

    % The same narrow bin edges are used for both distributions.
    sharedEdges = 0.25:0.025:2.25;

    histogram( ...
        axesBorders, ...
        BootBorderSigPre, ...
        sharedEdges, ...
        'FaceColor',colourPre, ...
        'EdgeColor',[0.80 0.05 0.05], ...
        'FaceAlpha',0.62, ...
        'LineWidth',0.35);

    histogram( ...
        axesBorders, ...
        BootBorderSigPost, ...
        sharedEdges, ...
        'FaceColor',colourPost, ...
        'EdgeColor',[0.05 0.08 0.80], ...
        'FaceAlpha',0.62, ...
        'LineWidth',0.35);

    xlabel(axesBorders,'PPS Border (m)');
    ylabel(axesBorders,'Frequency');
    xlim(axesBorders,[0.25 2.25]);
    xticks(axesBorders,0.5:0.5:2.0);
    style_wp3_axes(axesBorders);

    text(axesBorders,0.97,0.97,'a', ...
        'Units','normalized', ...
        'HorizontalAlignment','right', ...
        'VerticalAlignment','top', ...
        'FontSize',13, ...
        'FontName','Arial');

    %% Figure 3: Post-training minus baseline distribution

    figDifference = figure(3);
    clf(figDifference);
    set(figDifference,'Color','w','Position',[100 100 535 510]);
    axesDifference = axes('Parent',figDifference); %#ok<LAXES>
    hold(axesDifference,'on');

    histogram( ...
        axesDifference, ...
        diffPostPre, ...
        60, ...
        'FaceColor',[0.55 0.20 0.70], ...
        'EdgeColor',[0.35 0.10 0.50], ...
        'FaceAlpha',0.75, ...
        'LineWidth',0.35);

    xline( ...
        axesDifference, ...
        0, ...
        '--k', ...
        'LineWidth',1.5, ...
        'HandleVisibility','off');

    xline( ...
        axesDifference, ...
        mean(diffPostPre), ...
        '-r', ...
        'LineWidth',2, ...
        'HandleVisibility','off');

    xlabel(axesDifference,'Post-training - Baseline PPS Border (m)');
    ylabel(axesDifference,'Frequency');
    style_wp3_axes(axesDifference);

    %% Save figures

    exportgraphics( ...
        figFit, ...
        fullfile( ...
            dataFolder, ...
            'WP4_PPS_sigmoid_fits.png'), ...
        'Resolution',300);

    exportgraphics( ...
        figBorders, ...
        fullfile( ...
            dataFolder, ...
            'WP4_PPS_bootstrap_borders.png'), ...
        'Resolution',300);

    exportgraphics( ...
        figDifference, ...
        fullfile( ...
            dataFolder, ...
            'WP4_PPS_bootstrap_difference.png'), ...
        'Resolution',300);
end

%% -------------------- LOCAL FUNCTIONS --------------------

function style_wp3_axes(targetAxes)

    % Shared visual style used by the principal WP3 figures
    box(targetAxes,'off');
    pbaspect(targetAxes,[1 1 1]);

    set(targetAxes, ...
        'Color','w', ...
        'FontName','Arial', ...
        'FontSize',13, ...
        'LineWidth',2.2, ...
        'TickDir','out', ...
        'TickLength',[0.025 0.025], ...
        'XColor','k', ...
        'YColor','k', ...
        'Layer','top');
end

function draw_wp3_border_arrow( ...
    targetAxes,xPosition,arrowColour,yTop)

    % Data-coordinate equivalent of the double-headed PPS-border arrows
    % used in WP3. These objects remain aligned when the figure is resized
    % or exported.
    yBottom = 0.012;

    plot( ...
        targetAxes, ...
        [xPosition xPosition], ...
        [yBottom yTop], ...
        '-', ...
        'Color',arrowColour, ...
        'LineWidth',1.4, ...
        'HandleVisibility','off');

    plot( ...
        targetAxes, ...
        xPosition, ...
        yTop, ...
        '^', ...
        'MarkerFaceColor',arrowColour, ...
        'MarkerEdgeColor',arrowColour, ...
        'MarkerSize',7, ...
        'HandleVisibility','off');

    plot( ...
        targetAxes, ...
        xPosition, ...
        yBottom, ...
        'v', ...
        'MarkerFaceColor',arrowColour, ...
        'MarkerEdgeColor',arrowColour, ...
        'MarkerSize',7, ...
        'HandleVisibility','off');
end

function cleanedTrials = remove_wp3_outliers( ...
    trials,cutoff)

    trials = trials(isfinite(trials));

    if isempty(trials)
        cleanedTrials = trials;
        return
    end

    currentMean = mean(trials);
    currentSD = std(trials);

    % WP3 retained all trials when the SD was zero
    if isfinite(currentSD) && currentSD > 0

        zScores = abs( ...
            (trials-currentMean)./currentSD);

        cleanedTrials = ...
            trials(zScores < cutoff);

    else
        cleanedTrials = trials;
    end
end

function [bootMeanRT,bootBorder,bootR2,nAttempts] = ...
    run_wp3_bootstrap( ...
        conditionData, ...
        distances, ...
        cutoff, ...
        nBootstrap, ...
        minimumFitR2, ...
        maxAttempts, ...
        eqsig, ...
        fitOptions, ...
        seedOffset, ...
        showProgress, ...
        conditionLabel)

    nDistances = numel(distances);

    bootMeanRT = ...
        nan(nDistances,nBootstrap);

    bootBorder = ...
        nan(1,nBootstrap);

    bootR2 = ...
        nan(1,nBootstrap);

    nAccepted = 0;
    nAttempts = 0;

    while nAccepted < nBootstrap && ...
            nAttempts < maxAttempts

        nAttempts = nAttempts + 1;

        % Deterministic but different resampling
        % on every bootstrap attempt
        rng(seedOffset+nAttempts,'twister');

        bootstrapMeans = ...
            nan(nDistances,1);

        for d = 1:nDistances

            currentData = ...
                conditionData{d};

            nTrials = ...
                size(currentData,1);

            if nTrials == 0
                break
            end

            sampledIndices = ...
                randi(nTrials,nTrials,1);

            sampledRT = ...
                currentData(sampledIndices,2);

            sampledRT = ...
                remove_wp3_outliers( ...
                    sampledRT,cutoff);

            if isempty(sampledRT)
                break
            end

            bootstrapMeans(d) = ...
                mean(sampledRT,'omitnan');
        end

        if ~all(isfinite(bootstrapMeans))
            continue
        end

        denominator = ...
            max(bootstrapMeans) - ...
            min(bootstrapMeans);

        if ~isfinite(denominator) || ...
                denominator <= eps
            continue
        end

        normalisedMeans = ...
            (bootstrapMeans-min(bootstrapMeans)) ./ ...
            denominator;

        try

            [fitObject,goodness] = fit( ...
                distances, ...
                normalisedMeans, ...
                eqsig, ...
                fitOptions);

            currentR2 = ...
                goodness.rsquare;

            currentBorder = ...
                fitObject.x0;

        catch
            continue
        end

        % Same accepted-fit rule used in WP3
        if ~isfinite(currentR2) || ...
                currentR2 < minimumFitR2 || ...
                ~isfinite(currentBorder)

            continue
        end

        nAccepted = nAccepted + 1;

        bootMeanRT(:,nAccepted) = ...
            bootstrapMeans;

        bootBorder(nAccepted) = ...
            currentBorder;

        bootR2(nAccepted) = ...
            currentR2;

        if showProgress == 1 && ...
                (mod(nAccepted,1000) == 0 || ...
                 nAccepted == nBootstrap)

            fprintf( ...
                '%s: %d/%d accepted fits (%d attempts).\n', ...
                conditionLabel, ...
                nAccepted, ...
                nBootstrap, ...
                nAttempts);
        end
    end

    if nAccepted < nBootstrap

        error(['Only %d of %d required %s bootstrap fits ' ...
            'were accepted after %d attempts. Inspect the ' ...
            'data or increase maxAttempts.'], ...
            nAccepted, ...
            nBootstrap, ...
            conditionLabel, ...
            nAttempts);
    end
end
