%% WP4 SPEEDPAD PRELIMINARY ANALYSIS
% Standalone analysis that reads the WP4 SpeedPad Excel dataset directly.
%
% Design:
%   - Within-participant Pull Training and Control conditions
%   - First assessment = assessment before the condition/interval
%   - Second assessment = assessment after the condition/interval
%   - Primary outcome = number of hits during the two-minute SpeedPad task
%
% Primary analysis:
%   Change_Intervention = Intervention_TEST2 - Intervention_TEST1
%   Change_Control      = Control_TEST2 - Control_TEST1
%   Interaction contrast = Change_Intervention - Change_Control
%
% The exact two-sided sign-flip test on the within-participant
% difference-in-change contrast is the primary inferential analysis.
% A paired-samples t-test on the two change scores is reported as a
% complementary parametric sensitivity analysis. Both tests are calculated
% locally and do not require Statistics and Machine Learning Toolbox.

clear; close all; clc;

dbstop if error
% dbstop if warning

%% ======================== USER SETTINGS ==============================

% Full path to the Excel workbook. This is the only path that normally
% needs to be changed. Analysis outputs are saved beside the workbook.
dataFile = '';

% Worksheet containing the SpeedPad data.
sheetName = 'Sheet1';

outputFolder = fileparts(dataFile);

if isempty(outputFolder)
    outputFolder = pwd;
end

% All SpeedPad trials currently lasted two minutes.
taskDurationMinutes = 2;

% Set to true to create and export the figures.
makeFigures = true;

% Set to true to attempt the equivalent 2 x 2 repeated-measures ANOVA.
% The primary change-score analysis below is performed in all cases.
runRepeatedMeasuresANOVA = true;

%% ======================== IMPORT EXCEL DATA ==========================

if ~isfile(dataFile)
    error(['The SpeedPad Excel file was not found:\n%s\n' ...
        'Update dataFile in USER SETTINGS.'],dataFile);
end

rawData = readcell(dataFile,'Sheet',sheetName);

% Expected source layout:
%   A  = participant SN
%   B  = Intervention TEST1 label
%   C  = Intervention TEST1 Hits
%   D  = Intervention TEST1 Misses
%   E  = Intervention TEST2 label
%   F  = Intervention TEST2 Hits
%   G  = Intervention TEST2 Misses
%   H  = blank separator
%   I  = Control TEST1 label
%   J  = Control TEST1 Hits
%   K  = Control TEST1 Misses
%   L  = Control TEST2 label
%   M  = Control TEST2 Hits
%   N  = Control TEST2 Misses

if size(rawData,1) < 2 || size(rawData,2) < 14
    error(['The workbook does not match the expected SpeedPad layout. ' ...
        'Expected data in columns A:N.']);
end

if ~strcmpi(strtrim(string(rawData{1,1})),'SN')
    error('Cell A1 must contain the participant header SN.');
end

% Detect participant rows from numeric values in column A. Blank formatted
% rows beneath the dataset are ignored automatically.
participantCandidates = extract_speedpad_counts( ...
    rawData(2:end,1),false,'SN');
participantRowMask = isfinite(participantCandidates);

if ~any(participantRowMask)
    error('No participant rows were detected in column A.');
end

participantID = participantCandidates(participantRowMask);
participantRows = rawData(1+find(participantRowMask),:);

% Confirm that condition labels have not shifted to different columns.
interventionLabels1 = strtrim(string(participantRows(:,2)));
interventionLabels2 = strtrim(string(participantRows(:,5)));
controlLabels1 = strtrim(string(participantRows(:,9)));
controlLabels2 = strtrim(string(participantRows(:,12)));

if ~all(strcmpi(interventionLabels1,'Intervention')) || ...
        ~all(strcmpi(interventionLabels2,'Intervention'))
    error(['Intervention labels were not found in the expected ' ...
        'TEST1/TEST2 columns B and E.']);
end

if ~all(strcmpi(controlLabels1,'Control')) || ...
        ~all(strcmpi(controlLabels2,'Control'))
    error(['Control labels were not found in the expected ' ...
        'TEST1/TEST2 columns I and L.']);
end

% Values such as "122 (0.0%%)" are stored as text in Excel. The helper
% function extracts the first numeric value from every populated cell.
interventionTest1 = extract_speedpad_counts( ...
    participantRows(:,3),true,'Intervention TEST1 Hits');
interventionMissesTest1 = extract_speedpad_counts( ...
    participantRows(:,4),true,'Intervention TEST1 Misses');

interventionTest2 = extract_speedpad_counts( ...
    participantRows(:,6),true,'Intervention TEST2 Hits');
interventionMissesTest2 = extract_speedpad_counts( ...
    participantRows(:,7),true,'Intervention TEST2 Misses');

controlTest1 = extract_speedpad_counts( ...
    participantRows(:,10),true,'Control TEST1 Hits');
controlMissesTest1 = extract_speedpad_counts( ...
    participantRows(:,11),true,'Control TEST1 Misses');

controlTest2 = extract_speedpad_counts( ...
    participantRows(:,13),true,'Control TEST2 Hits');
controlMissesTest2 = extract_speedpad_counts( ...
    participantRows(:,14),true,'Control TEST2 Misses');

%% ======================== VALIDATION =================================

dataColumns = { ...
    interventionTest1,interventionTest2,controlTest1,controlTest2, ...
    interventionMissesTest1,interventionMissesTest2, ...
    controlMissesTest1,controlMissesTest2};

nParticipants = numel(participantID);

if nParticipants < 2
    error('At least two participants are required.');
end

for columnNumber = 1:numel(dataColumns)
    currentColumn = dataColumns{columnNumber};

    if numel(currentColumn) ~= nParticipants
        error('All data columns must contain one value per participant.');
    end

    if any(~isfinite(currentColumn))
        error('Missing or non-finite values were detected.');
    end

    if any(currentColumn < 0) || ...
            any(abs(currentColumn-round(currentColumn)) > eps)
        error('SpeedPad Hits and Misses must be non-negative integers.');
    end
end

if numel(unique(participantID)) ~= nParticipants
    error('Participant identifiers must be unique.');
end

if taskDurationMinutes <= 0
    error('taskDurationMinutes must be greater than zero.');
end

if ~isfolder(outputFolder)
    mkdir(outputFolder);
end

%% ======================== DERIVED VARIABLES ==========================

changeIntervention = interventionTest2-interventionTest1;
changeControl = controlTest2-controlTest1;

% Primary Time-by-Condition interaction contrast.
differenceInChange = changeIntervention-changeControl;

interventionTest1PerMinute = interventionTest1/taskDurationMinutes;
interventionTest2PerMinute = interventionTest2/taskDurationMinutes;
controlTest1PerMinute = controlTest1/taskDurationMinutes;
controlTest2PerMinute = controlTest2/taskDurationMinutes;

participantTable = table( ...
    participantID, ...
    interventionTest1, ...
    interventionTest2, ...
    changeIntervention, ...
    controlTest1, ...
    controlTest2, ...
    changeControl, ...
    differenceInChange, ...
    interventionTest1PerMinute, ...
    interventionTest2PerMinute, ...
    controlTest1PerMinute, ...
    controlTest2PerMinute, ...
    'VariableNames',{ ...
    'ParticipantID', ...
    'Intervention_TEST1_Hits', ...
    'Intervention_TEST2_Hits', ...
    'Intervention_Change', ...
    'Control_TEST1_Hits', ...
    'Control_TEST2_Hits', ...
    'Control_Change', ...
    'DifferenceInChange', ...
    'Intervention_TEST1_HitsPerMin', ...
    'Intervention_TEST2_HitsPerMin', ...
    'Control_TEST1_HitsPerMin', ...
    'Control_TEST2_HitsPerMin'});

%% ======================== DESCRIPTIVE STATISTICS =====================

conditionLabel = ["Pull Training";"Control"];

test1Mean = [mean(interventionTest1);mean(controlTest1)];
test1SD = [std(interventionTest1);std(controlTest1)];
test1SEM = test1SD/sqrt(nParticipants);

test2Mean = [mean(interventionTest2);mean(controlTest2)];
test2SD = [std(interventionTest2);std(controlTest2)];
test2SEM = test2SD/sqrt(nParticipants);

changeMean = [mean(changeIntervention);mean(changeControl)];
changeSD = [std(changeIntervention);std(changeControl)];
changeSEM = changeSD/sqrt(nParticipants);

summaryTable = table( ...
    conditionLabel, ...
    repmat(nParticipants,2,1), ...
    test1Mean,test1SD,test1SEM, ...
    test2Mean,test2SD,test2SEM, ...
    changeMean,changeSD,changeSEM, ...
    'VariableNames',{ ...
    'Condition','N', ...
    'TEST1_Mean','TEST1_SD','TEST1_SEM', ...
    'TEST2_Mean','TEST2_SD','TEST2_SEM', ...
    'Change_Mean','Change_SD','Change_SEM'});

%% ======================== PRIMARY ANALYSIS ===========================

alpha = 0.05;

% Complementary parametric comparison of the Intervention and Control
% change scores. This local implementation does not require Statistics
% Toolbox.
[hInteraction,pInteraction,ciInteraction,statsInteraction] = ...
    paired_ttest_base(changeIntervention,changeControl,alpha);

meanDifferenceInChange = mean(differenceInChange);
sdDifferenceInChange = std(differenceInChange);
semDifferenceInChange = ...
    sdDifferenceInChange/sqrt(nParticipants);

% Paired-samples standardised effect size.
cohensDzInteraction = ...
    meanDifferenceInChange/sdDifferenceInChange;

% Descriptive/preliminary pre-to-post tests within each condition.
[hIntervention,pIntervention,ciIntervention,statsIntervention] = ...
    paired_ttest_base(interventionTest2,interventionTest1,alpha);

[hControl,pControl,ciControl,statsControl] = ...
    paired_ttest_base(controlTest2,controlTest1,alpha);

cohensDzIntervention = ...
    mean(changeIntervention)/std(changeIntervention);
cohensDzControl = ...
    mean(changeControl)/std(changeControl);

% Exact two-sided sign-flip permutation test on the same within-participant
% interaction contrast. This is the primary inferential analysis and
% requires no Statistics Toolbox.
[pSignFlip,signFlipStatistic,nSignFlipPermutations,signFlipMethod] = ...
    sign_flip_test_base(differenceInChange);
rejectNullSignFlip = pSignFlip < alpha;

primaryResultsTable = table( ...
    nParticipants, ...
    mean(changeIntervention), ...
    std(changeIntervention), ...
    mean(changeControl), ...
    std(changeControl), ...
    meanDifferenceInChange, ...
    sdDifferenceInChange, ...
    semDifferenceInChange, ...
    ciInteraction(1), ...
    ciInteraction(2), ...
    statsInteraction.tstat, ...
    statsInteraction.df, ...
    pInteraction, ...
    hInteraction, ...
    cohensDzInteraction, ...
    signFlipStatistic, ...
    pSignFlip, ...
    rejectNullSignFlip, ...
    nSignFlipPermutations, ...
    signFlipMethod, ...
    'VariableNames',{ ...
    'N', ...
    'InterventionChange_Mean', ...
    'InterventionChange_SD', ...
    'ControlChange_Mean', ...
    'ControlChange_SD', ...
    'DifferenceInChange_Mean', ...
    'DifferenceInChange_SD', ...
    'DifferenceInChange_SEM', ...
    'CI95_Lower', ...
    'CI95_Upper', ...
    'TStatistic', ...
    'DegreesOfFreedom', ...
    'PValue_TwoSided', ...
    'RejectNullAt_0_05', ...
    'CohensDz', ...
    'SignFlip_ObservedMean', ...
    'SignFlip_PValue_TwoSided', ...
    'SignFlip_RejectNullAt_0_05', ...
    'SignFlip_NumberOfPermutations', ...
    'SignFlip_Method'});

secondaryResultsTable = table( ...
    ["Pull Training: Second - First";"Control: Second - First"], ...
    [mean(changeIntervention);mean(changeControl)], ...
    [std(changeIntervention);std(changeControl)], ...
    [ciIntervention(1);ciControl(1)], ...
    [ciIntervention(2);ciControl(2)], ...
    [statsIntervention.tstat;statsControl.tstat], ...
    [statsIntervention.df;statsControl.df], ...
    [pIntervention;pControl], ...
    [hIntervention;hControl], ...
    [cohensDzIntervention;cohensDzControl], ...
    'VariableNames',{ ...
    'Comparison','MeanChange','SDChange','CI95_Lower','CI95_Upper', ...
    'TStatistic','DegreesOfFreedom','PValue_TwoSided', ...
    'RejectNullAt_0_05','CohensDz'});

%% ======================== OPTIONAL 2 x 2 RM-ANOVA ===================

ranovaTable = table();

if runRepeatedMeasuresANOVA && exist('fitrm','file') == 2
    try
        wideTable = table( ...
            participantID, ...
            interventionTest1, ...
            interventionTest2, ...
            controlTest1, ...
            controlTest2, ...
            'VariableNames',{ ...
            'ParticipantID', ...
            'Intervention_TEST1', ...
            'Intervention_TEST2', ...
            'Control_TEST1', ...
            'Control_TEST2'});

        withinDesign = table( ...
            categorical(["Intervention";"Intervention"; ...
                         "Control";"Control"]), ...
            categorical(["TEST1";"TEST2";"TEST1";"TEST2"]), ...
            'VariableNames',{'Condition','Time'});

        repeatedModel = fitrm( ...
            wideTable, ...
            'Intervention_TEST1-Control_TEST2 ~ 1', ...
            'WithinDesign',withinDesign);

        ranovaTable = ranova( ...
            repeatedModel,'WithinModel','Condition*Time');

    catch anovaError
        warning('Repeated-measures ANOVA was not completed: %s', ...
            anovaError.message);
    end
end

%% ======================== COMMAND-WINDOW OUTPUT ======================

fprintf('\n============================================================\n');
fprintf('WP4 SPEEDPAD PRELIMINARY RESULTS\n');
fprintf('============================================================\n');
fprintf('Participants included: %d\n',nParticipants);
fprintf('Task duration: %.1f minutes per assessment\n\n', ...
    taskDurationMinutes);

fprintf('Training Intervention:\n');
fprintf('  First assessment: M = %.2f, SD = %.2f hits\n', ...
    mean(interventionTest1),std(interventionTest1));
fprintf('  Second assessment: M = %.2f, SD = %.2f hits\n', ...
    mean(interventionTest2),std(interventionTest2));
fprintf('  Change: M = %.2f, SD = %.2f hits\n\n', ...
    mean(changeIntervention),std(changeIntervention));

fprintf('Control:\n');
fprintf('  First assessment: M = %.2f, SD = %.2f hits\n', ...
    mean(controlTest1),std(controlTest1));
fprintf('  Second assessment: M = %.2f, SD = %.2f hits\n', ...
    mean(controlTest2),std(controlTest2));
fprintf('  Change: M = %.2f, SD = %.2f hits\n\n', ...
    mean(changeControl),std(changeControl));

fprintf('Difference-in-change contrast (Time x Condition):\n');
fprintf('  Mean difference in change = %.2f hits\n', ...
    meanDifferenceInChange);
fprintf(['  Primary exact two-sided sign-flip test: ' ...
    'mean = %.2f, p = %.5f\n'],signFlipStatistic,pSignFlip);
fprintf('  Method: %s (%d permutations)\n', ...
    char(signFlipMethod),nSignFlipPermutations);

fprintf('  Complementary paired-samples t test:\n');
fprintf('    95%% CI = [%.2f, %.2f]\n', ...
    ciInteraction(1),ciInteraction(2));
fprintf('    t(%d) = %.3f, p = %.5f\n', ...
    statsInteraction.df,statsInteraction.tstat,pInteraction);
fprintf('    Cohen''s dz = %.3f\n',cohensDzInteraction);

fprintf('\nIndividual difference-in-change values:\n');
disp(table(participantID,differenceInChange, ...
    'VariableNames',{'ParticipantID','DifferenceInChange'}));

if all(interventionMissesTest1 == 0) && ...
        all(interventionMissesTest2 == 0) && ...
        all(controlMissesTest1 == 0) && ...
        all(controlMissesTest2 == 0)

    fprintf(['Misses were zero in all sessions; no inferential analysis ' ...
        'of misses was performed.\n']);
end

fprintf('============================================================\n');

%% ======================== SAVE NUMERICAL OUTPUTS =====================

writetable(participantTable, ...
    fullfile(outputFolder,'WP4_SpeedPad_participant_results.csv'));

writetable(summaryTable, ...
    fullfile(outputFolder,'WP4_SpeedPad_descriptive_summary.csv'));

writetable(primaryResultsTable, ...
    fullfile(outputFolder,'WP4_SpeedPad_primary_results.csv'));

writetable(secondaryResultsTable, ...
    fullfile(outputFolder,'WP4_SpeedPad_secondary_results.csv'));

if ~isempty(ranovaTable)
    writetable(ranovaTable, ...
        fullfile(outputFolder,'WP4_SpeedPad_repeated_measures_ANOVA.csv'), ...
        'WriteRowNames',true);
end

save(fullfile(outputFolder,'WP4_SpeedPad_results.mat'));

%% ======================== FIGURES ====================================

if makeFigures
    interventionColour = [0.90 0.12 0.12];
    controlColour = [0.15 0.25 0.90];
    lightGrey = [0.78 0.78 0.78];

    % Figure 1: individual and group first-to-second performance.
    figPerformance = figure(1); clf(figPerformance);
    set(figPerformance,'Color','w','Position',[100 100 610 520]);
    axPerformance = axes('Parent',figPerformance); %#ok<LAXES>
    hold(axPerformance,'on');

    interventionX = [0.96 1.96];
    controlX = [1.04 2.04];

    for participantNumber = 1:nParticipants
        plot(axPerformance,interventionX, ...
            [interventionTest1(participantNumber), ...
             interventionTest2(participantNumber)], ...
            '-','Color',[1.00 0.72 0.72], ...
            'LineWidth',0.8,'HandleVisibility','off');

        plot(axPerformance,controlX, ...
            [controlTest1(participantNumber), ...
             controlTest2(participantNumber)], ...
            '-','Color',[0.72 0.77 1.00], ...
            'LineWidth',0.8,'HandleVisibility','off');
    end

    hIntervention = errorbar(axPerformance,interventionX, ...
        [mean(interventionTest1),mean(interventionTest2)], ...
        [std(interventionTest1),std(interventionTest2)]/sqrt(nParticipants), ...
        '-o','Color',interventionColour, ...
        'MarkerFaceColor','w','MarkerEdgeColor',interventionColour, ...
        'MarkerSize',8,'LineWidth',2.8,'CapSize',10);

    hControl = errorbar(axPerformance,controlX, ...
        [mean(controlTest1),mean(controlTest2)], ...
        [std(controlTest1),std(controlTest2)]/sqrt(nParticipants), ...
        '-o','Color',controlColour, ...
        'MarkerFaceColor','w','MarkerEdgeColor',controlColour, ...
        'MarkerSize',8,'LineWidth',2.8,'CapSize',10);

    xlim(axPerformance,[0.72 2.28]);
    ylim(axPerformance,[40 200]);
    yticks(axPerformance,40:20:200);
    xticks(axPerformance,[1 2]);
    xticklabels(axPerformance, ...
    {'FIRST ASSESSMENT','SECOND ASSESSMENT'});
    ylabel(axPerformance,'Hits (2 min)');
    style_speedpad_axes(axPerformance);
    legend(axPerformance,[hIntervention,hControl], ...
    {'PULL TRAINING','CONTROL'}, ...
    'Location','northwest','Box','on','FontSize',9);

    % Figure 2: paired condition-specific change scores.
    figChange = figure(2); clf(figChange);
    set(figChange,'Color','w','Position',[100 100 680 520]);
    axChange = axes('Parent',figChange); %#ok<LAXES>
    hold(axChange,'on');

    for participantNumber = 1:nParticipants
        plot(axChange,[1 2], ...
            [changeControl(participantNumber), ...
             changeIntervention(participantNumber)], ...
            '-','Color',lightGrey,'LineWidth',1.1, ...
            'HandleVisibility','off');

        plot(axChange,1,changeControl(participantNumber),'o', ...
            'MarkerFaceColor','w','MarkerEdgeColor',controlColour, ...
            'MarkerSize',7,'LineWidth',1.3, ...
            'HandleVisibility','off');

        plot(axChange,2,changeIntervention(participantNumber),'o', ...
            'MarkerFaceColor','w','MarkerEdgeColor',interventionColour, ...
            'MarkerSize',7,'LineWidth',1.3, ...
            'HandleVisibility','off');
    end

    errorbar(axChange,1,mean(changeControl), ...
        std(changeControl)/sqrt(nParticipants), ...
        'o','Color',controlColour,'MarkerFaceColor',controlColour, ...
        'MarkerSize',9,'LineWidth',2.2,'CapSize',12, ...
        'HandleVisibility','off');

    errorbar(axChange,2,mean(changeIntervention), ...
        std(changeIntervention)/sqrt(nParticipants), ...
        'o','Color',interventionColour, ...
        'MarkerFaceColor',interventionColour, ...
        'MarkerSize',9,'LineWidth',2.2,'CapSize',12, ...
        'HandleVisibility','off');

    yline(axChange,0,'--k','LineWidth',1.2, ...
        'HandleVisibility','off');
    xlim(axChange,[0.65 2.35]);
    ylim(axChange,[0 100]);
    xticks(axChange,[1 2]);
    xticklabels(axChange, ...
    {'CONTROL','PULL TRAINING'});
    ylabel(axChange,'Change in Hits','FontSize',12);
    style_speedpad_axes(axChange);

    exportgraphics(figPerformance, ...
        fullfile(outputFolder, ...
        'WP4_SpeedPad_first_second_assessments.png'), ...
        'Resolution',300);

    exportgraphics(figChange, ...
        fullfile(outputFolder,'WP4_SpeedPad_change_scores.png'), ...
        'Resolution',300);
end

fprintf('\nAll SpeedPad outputs were saved to:\n%s\n',outputFolder);

%% ======================== LOCAL FUNCTION =============================

function [pValue,observedStatistic,nPermutations,method] = ...
    sign_flip_test_base(differences)

    % Two-sided paired sign-flip permutation test implemented using only
    % base MATLAB. The statistic is the mean within-participant contrast.
    % For up to 20 participants, every possible sign allocation is tested.
    % For larger samples, a reproducible Monte Carlo approximation is used
    % to avoid excessive memory use and computation time.
    differences = differences(:);

    if any(~isfinite(differences))
        error(['The sign-flip test received missing or ' ...
            'non-finite values.']);
    end

    sampleSize = numel(differences);

    if sampleSize < 1
        error('At least one paired contrast is required.');
    end

    observedStatistic = mean(differences);
    comparisonTolerance = ...
        1e-12*max(1,abs(observedStatistic));
    maximumExactSampleSize = 20;

    if sampleSize <= maximumExactSampleSize
        nPermutations = 2^sampleSize;
        method = "Exact enumeration";
        extremeCount = 0;
        chunkSize = 100000;

        for firstPermutation = 0:chunkSize:(nPermutations-1)
            lastPermutation = min( ...
                firstPermutation+chunkSize-1,nPermutations-1);
            permutationIDs = uint64( ...
                (firstPermutation:lastPermutation)');
            permutedSums = zeros(numel(permutationIDs),1);

            for participantNumber = 1:sampleSize
                currentSigns = 2*double(bitget( ...
                    permutationIDs,participantNumber))-1;
                permutedSums = permutedSums + ...
                    currentSigns*differences(participantNumber);
            end

            permutedStatistics = permutedSums/sampleSize;
            extremeCount = extremeCount + sum( ...
                abs(permutedStatistics) >= ...
                abs(observedStatistic)-comparisonTolerance);
        end

        pValue = extremeCount/nPermutations;
    else
        % Reproducible approximation for future larger samples.
        nPermutations = 100000;
        method = "Monte Carlo approximation";
        rng(20260804,'twister');
        extremeCount = 0;
        chunkSize = 10000;
        permutationsCompleted = 0;

        while permutationsCompleted < nPermutations
            currentChunk = min( ...
                chunkSize,nPermutations-permutationsCompleted);
            randomSigns = 2*(rand(currentChunk,sampleSize) >= 0.5)-1;
            permutedStatistics = mean( ...
                randomSigns.*differences',2);
            extremeCount = extremeCount + sum( ...
                abs(permutedStatistics) >= ...
                abs(observedStatistic)-comparisonTolerance);
            permutationsCompleted = ...
                permutationsCompleted+currentChunk;
        end

        % Plus-one correction for a Monte Carlo randomisation p-value.
        pValue = (extremeCount+1)/(nPermutations+1);
    end

    pValue = min(max(pValue,0),1);
end

function [rejectNull,pValue,confidenceInterval,stats] = ...
    paired_ttest_base(firstMeasure,secondMeasure,alpha)

    % Two-sided paired-samples t-test implemented with base MATLAB.
    % The test is applied to firstMeasure-secondMeasure.
    differences = firstMeasure(:)-secondMeasure(:);

    if any(~isfinite(differences))
        error('The paired t-test received missing or non-finite values.');
    end

    sampleSize = numel(differences);

    if sampleSize < 2
        error('At least two paired observations are required.');
    end

    degreesOfFreedom = sampleSize-1;
    meanDifference = mean(differences);
    standardDeviation = std(differences);
    standardError = standardDeviation/sqrt(sampleSize);

    if standardError > 0
        tStatistic = meanDifference/standardError;
        pValue = student_t_two_sided_p_base( ...
            tStatistic,degreesOfFreedom);

        criticalT = student_t_inverse_base( ...
            1-alpha/2,degreesOfFreedom);

        confidenceInterval = meanDifference + ...
            [-1 1]*criticalT*standardError;
    else
        if meanDifference == 0
            tStatistic = 0;
            pValue = 1;
        else
            tStatistic = sign(meanDifference)*Inf;
            pValue = 0;
        end

        confidenceInterval = [meanDifference meanDifference];
    end

    pValue = min(max(pValue,0),1);
    rejectNull = pValue < alpha;

    stats = struct( ...
        'tstat',tStatistic, ...
        'df',degreesOfFreedom, ...
        'sd',standardDeviation);
end

function pValue = student_t_two_sided_p_base( ...
    tStatistic,degreesOfFreedom)

    % For a Student-t variable, the two-sided tail probability can be
    % calculated directly from the regularised incomplete beta function.
    if isinf(tStatistic)
        pValue = 0;
        return
    end

    betaArgument = degreesOfFreedom ./ ...
        (degreesOfFreedom+tStatistic.^2);

    pValue = betainc( ...
        betaArgument,degreesOfFreedom/2,0.5);
end

function tQuantile = student_t_inverse_base( ...
    probability,degreesOfFreedom)

    % Inverse Student-t CDF calculated from BETAINCINV. This replaces TINV,
    % which belongs to Statistics and Machine Learning Toolbox.
    if probability <= 0 || probability >= 1
        error('Student-t probability must be between zero and one.');
    end

    if probability == 0.5
        tQuantile = 0;
        return
    end

    if probability < 0.5
        tQuantile = -student_t_inverse_base( ...
            1-probability,degreesOfFreedom);
        return
    end

    twoSidedTail = 2*(1-probability);
    betaQuantile = betaincinv( ...
        twoSidedTail,degreesOfFreedom/2,0.5);

    tQuantile = sqrt( ...
        degreesOfFreedom*(1-betaQuantile)/betaQuantile);
end

function numericValues = extract_speedpad_counts( ...
    rawColumn,requireComplete,variableLabel)

    % Extract the first numeric value from cells formatted as, for example,
    % "122 (0.0%)". Numeric Excel cells are also accepted directly.
    numericValues = nan(numel(rawColumn),1);

    for rowNumber = 1:numel(rawColumn)
        currentValue = rawColumn{rowNumber};

        if isnumeric(currentValue) && isscalar(currentValue)
            if isfinite(currentValue)
                numericValues(rowNumber) = double(currentValue);
            end
            continue
        end

        currentText = strtrim(string(currentValue));

        if ismissing(currentText) || strlength(currentText) == 0
            continue
        end

        firstNumber = regexp( ...
            char(currentText), ...
            '[-+]?(?:\d+\.?\d*|\.\d+)', ...
            'match','once');

        if ~isempty(firstNumber)
            numericValues(rowNumber) = str2double(firstNumber);
        end
    end

    if requireComplete && any(~isfinite(numericValues))
        badRows = find(~isfinite(numericValues));
        error(['Could not extract a numeric value for %s in ' ...
            'participant-data row(s): %s.'], ...
            variableLabel,mat2str(badRows'));
    end
end

function style_speedpad_axes(targetAxes)
    box(targetAxes,'off');
    pbaspect(targetAxes,[1 1 1]);
    set(targetAxes, ...
        'Color','w', ...
        'FontName','Arial', ...
        'FontSize',13, ...
        'LineWidth',2.2, ...
        'TickDir','out', ...
        'TickLength',[0.025 0.025], ...
        'XColor','k', ...
        'YColor','k', ...
        'Layer','top');
end
